
---
title: "Hello, World!"
date: 2018-12-14
---

title: Dan The Man
author: Dan
email: detinsley1s@gmail.com
description: > # this means to ignore newlines until "baseurl:"
The best website ever.

# social links
twitter_username: @detinsley1s
github_username:  detinsley1s

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
